### ISSUE TITLE
Typo in Chapter 3 "Runnable Math" 

### ISSUE THREAD

**Issue by DeepakG123** [kevinsullivan/cs-dm#1]
"Althird, though you can’t see it here in this document, Dafny checks to ensure that no code ever calls this function with a value of n that is less than zero, and it proves to itself that the recursion is well founded. That is a lot more than you could ever expect to get programming in an imperative language like Python."

Type in the first word of paragraph number 13, should be "third" instead of Althird.

**Comment by kevinsullivan** [comment]
I think this typo is in the file, dross.rst, which is not part of the actual notes for class. Thanks though for the heads up.
