### ISSUE TITLE
List of typos in Chapter 7: Set Theory

### ISSUE THREAD

**Issue by Shrirag** [kevinsullivan/cs-dm#12]
Naive Set Theory:
setsm -> sets

Overly naive set theory:
containss -> contains

Display notation:
andin -> and in
var S:set<int> := { 1, 2, 3 }. -> var S:set<int> := { 1, 2, 3 };
var S := { 1, 2, 3 } -> var S := { 1, 2, 3 };

Subset
less and and less than or equal -> less than and less than or equal

Product set:
set s, t: s in S && t in T :: (s,t) -> set s, t | s in S && t in T  :: (s, t)
followed by a colon -> followed by a verticalbar

**Comment by kevinsullivan** [comment]
Thanks for this, Shrirag. Did you have a chance to play around with any  of
this in Dafny? It's pretty interesting. --Kevin

**Comment by Shrirag** [comment]
Yeah, I did a few of those sample exercises.

**Comment by kevinsullivan** [comment]
Fixed
