### ISSUE TITLE
Typos in Chapter 5

### ISSUE THREAD

**Issue by LnLou** [kevinsullivan/cs-dm#14]
Performance vs. Undertandability -> Understandability
2nd paragraph diferences -> differences

Turning Partial Functions into Total Functions
4th paragraph formula (4, {2, 2} -> (4, {2, 2})
6th paragraph Daphy should be Dafny

What is Dafny, Again?
1st paragraph tooset -> toolset

**Comment by kevinsullivan** [comment]
Thank you! Fixed.
