### ISSUE TITLE
Typo in "Problems with Imperative Code"

### ISSUE THREAD

**Issue by daherro** [kevinsullivan/cs-dm#5]
**In paragraph 4, the last sentence:**
_"The human mind is simpl not powerful enough to see what can happen when computations distant in time and in space (in the sense of being separated in the code) interact with each other."_

The word "simpl" should be spelled as "simply."

**In paragraph 5, the third sentence:**
_"A peice of code that assumes that y doesn’t change unless a change is made expliticly might fail catastrophically under such circumstances."_

The word "peice" should be spelled as "piece" and the word "expliticly" should be spelled as "explicitly."

-- Justin Nguyen (jtn5dr)

**Comment by kevinsullivan** [comment]
Fixed, thanks!
